import "core-js/modules/es.object.assign";
import "core-js/modules/es.object.to-string";
import "core-js/modules/es.array.iterator";
import "core-js/modules/es.array.from";
import "core-js/modules/es.string.at";
import "core-js/modules/es.string.from-code-point";
import "core-js/modules/es.string.iterator";
import "core-js/modules/web.url.constructor";
import "core-js/modules/web.url.parse";
import "core-js/modules/web.url-search-params.constructor";
URL.parse('http://a.b/c').pathname.at(-1);