import "core-js/modules/es.symbol.iterator";
import "core-js/modules/es.object.to-string";
import "core-js/modules/es.array.iterator";
import "core-js/modules/es.string.at";
import "core-js/modules/es.string.iterator";
import "core-js/modules/es.string.bold";
import "core-js/modules/web.dom-collections.iterator";
const items: string[] = ['hello'];
const [x]: unknown[] = items;
x.at(0).bold();