import "core-js/modules/es.symbol.iterator";
import "core-js/modules/es.object.to-string";
import "core-js/modules/es.array.iterator";
import "core-js/modules/es.string.repeat";
import "core-js/modules/es.number.to-fixed";
import "core-js/modules/es.string.iterator";
import "core-js/modules/web.dom-collections.iterator";
declare const [a, b]: [number, string];
a.toFixed(2);
b.repeat(3);