'use strict';
require('../../modules/es.array.iterator');
require('../../modules/es.array.entries');
require('../../modules/es.array.keys');
require('../../modules/es.object.to-string');
require('../../modules/web.dom-collections.iterator');
require('../../modules/web.dom-collections.entries');
require('../../modules/web.dom-collections.for-each');
require('../../modules/web.dom-collections.keys');
require('../../modules/web.dom-collections.values');
