import "core-js/modules/es.object.from-entries";
import "core-js/modules/es.object.to-string";
import "core-js/modules/es.aggregate-error.constructor";
import "core-js/modules/es.promise.constructor";
import "core-js/modules/es.promise.catch";
import "core-js/modules/es.promise.finally";
import "core-js/modules/es.promise.resolve";
import "core-js/modules/es.promise.any";
import "core-js/modules/es.array.iterator";
import "core-js/modules/es.array.from";
import "core-js/modules/es.global-this";
import "core-js/modules/es.map.constructor";
import "core-js/modules/es.map.species";
import "core-js/modules/es.map.group-by";
import "core-js/modules/es.map.get-or-insert";
import "core-js/modules/es.map.get-or-insert-computed";
import "core-js/modules/es.string.iterator";
import "core-js/modules/es.weak-map.constructor";
import "core-js/modules/es.weak-map.get-or-insert";
import "core-js/modules/es.weak-map.get-or-insert-computed";
import "core-js/modules/web.dom-collections.iterator";
import "core-js/modules/web.self";
// In usage-global a realm selection with effectful arms stays as written, its effects run natively, and
// the constructor read off it injects that constructor's family.
let e = 0;
const c = pick();
const user = make();
export const viaAlternate = (c ? globalThis : (e++, self)).Promise.any;
export const viaBoth = (c ? (e++, globalThis) : (e--, self)).Map.groupBy;
export const viaCall = (c ? (e++, globalThis) : globalThis).Array.from([1]);
export const viaCtor = (c ? (e++, self) : globalThis).WeakMap;
export const keepsUserArm = (c ? (e++, globalThis) : user).Object.fromEntries;
export { e };