/// <reference types="../core-js-types/async-iterable" />
/// <reference types="../core-js-types/async-iterator-object" />
/// <reference types="../core-js-types/promise" />

// Motivation: Has dependencies on internal types, e.g. AsyncIterable, AsyncIteratorObject
// Motivation: Iterator until TS 5.6 used undefined as TNext defaults

// proposal stage: 2
// https://github.com/tc39/proposal-async-iterator-helpers

declare namespace CoreJS {
  export interface CoreJSAsyncIteratorConstructor {
    /**
     * Creates an `AsyncIterator` from an iterable object
     * @param iterable - An `AsyncIterable`, `Iterable`, or `AsyncIterator` to convert to an `AsyncIterator`
     * @returns A new `AsyncIterator` instance
     */
    from<T>(iterable: CoreJSAsyncIterable<T> | Iterable<T> | CoreJSAsyncIteratorObject<T>): CoreJSAsyncIteratorObject<T>;
  }

  export interface CoreJSAsyncIterator<T, TReturn = any, TNext = any> {

    /**
     * Drops elements from the iterator until the limit is reached
     * @param limit - The number of elements to drop
     * @returns A new `AsyncIterator`
     */
    drop(limit: number): CoreJSAsyncIteratorObject<T>;

    /**
     * Check if every value generated by the iterator passes the `predicate` function.
     * @param predicate - A function that tests each element of the iterator
     * @returns A promise that resolves to `true` if all elements pass the test, otherwise `false`
     */
    every(predicate: (value: T, index: number) => boolean): CoreJSPromise<boolean>;

    /**
     * Creates a new `AsyncIterator` that contains only the elements that pass the `predicate` function.
     * @param predicate - A function that tests each element of the iterator
     * @returns A new `AsyncIterator`
     */
    filter(predicate: (value: T, index: number) => boolean): CoreJSAsyncIteratorObject<T>;

    /**
     * Finds the first element in the iterator that satisfies the `predicate` function.
     * @param predicate - A function that tests each element of the iterator
     * @returns A `Promise` that resolves to the found element, or `undefined` if no element satisfies the `predicate`
     */
    find(predicate: (value: T, index: number) => boolean): CoreJSPromise<T>;

    /**
     * Creates a new `AsyncIterator` by applying the `mapper` function to each element of the original iterator and flattening the result.
     * @param mapper - A function that transforms each element of the iterator
     * @returns A new `AsyncIterator`
     */
    flatMap(mapper: (value: T, index: number) => any): CoreJSAsyncIteratorObject<any>;

    /**
     * Executes a provided function once for each element in the iterator.
     * @param callbackFn - A function that is called for each element of the iterator
     * @returns A `Promise` that resolves when all elements have been processed
     */
    forEach(callbackFn: (value: T, index: number) => void): CoreJSPromise<void>;

    /**
     * Creates a new `AsyncIterator` by applying the `mapper` function to each element of the original iterator.
     * @param mapper - A function that transforms each element of the iterator
     * @returns A new `AsyncIterator`
     */
    map(mapper: (value: T, index: number) => any): CoreJSAsyncIteratorObject<T>;

    /**
     * Reduces the elements of the iterator to a single value using the `reducer` function.
     * @param reducer - A function that combines two elements of the iterator
     * @param initialValue - An optional initial value to start the reduction
     * @returns A `Promise` that resolves to the reduced value
     */
    reduce(reducer: (accumulator: any, value: T, index: number) => any, initialValue?: any): CoreJSPromise<any>;

    /**
     * Checks if any value in the iterator matches a given `predicate`
     * @param predicate - A function that tests each element of the iterator
     * @returns A `Promise` that resolves to `true` if any element passes the `predicate`, otherwise `false`
     */
    some(predicate: (value: T, index: number) => boolean): CoreJSPromise<boolean>;

    /**
     * Creates a new `AsyncIterator` that yields only the first `limit` elements from the original iterator.
     * @param limit - The maximum number of elements to take
     * @returns A new `AsyncIterator`
     */
    take(limit: number): CoreJSAsyncIteratorObject<T>;

    /**
     * Collects all elements from the iterator into an array.
     * @returns A `Promise` that resolves to an array containing all elements from the iterator
     */
    toArray(): CoreJSPromise<T[]>;
  }

  var CoreJSAsyncIterator: CoreJSAsyncIteratorConstructor;

  interface CoreJSIterator<T, TReturn = any, TNext = undefined> extends Iterator<T, TReturn, TNext> {
    /**
     * Creates an `AsyncIterator` from the current `Iterator`
     * @returns A new `AsyncIterator` instance
     */
    toAsync(): CoreJSAsyncIteratorObject<T>;
  }
}
