// barrel re-export - preserves external import surface while logic lives in focused modules
export {
  ESM_MARKER_TYPES,
  TS_EXPR_WRAPPERS,
  createTypeAnnotationChecker,
  declaresRequireBinding,
  destructureReceiverSlot,
  detectCommonJS,
  findIifeArgForParam,
  findIifeCallSite,
  findTSRuntimeBindingInPath,
  flattenableHostSlot,
  getFallbackBranchSlots,
  getSuperTypeArgs,
  getTSRuntimeBindings,
  getTypeArgs,
  hasSideEffectfulSequencePrefix,
  hasTopLevelESM,
  isDeleteTarget,
  isForXWriteTarget,
  isASTNode,
  isAmbientBindingShape,
  isAmbientTypeDeclaration,
  isChainAssignment,
  isClassifiableReceiverArg,
  isFunctionParamDestructureParent,
  isMemberWriteOnlyContext,
  isTypeOnlyImportEquals,
  isInUpdateOperand,
  isSingleNestedProxyChain,
  isTSTypeOnlyIdentifier,
  isTSTypeOnlyIdentifierPath,
  isTypeOnlyImportBinding,
  isIdentifierPropValue,
  isSynthSimpleObjectPattern,
  isTaggedTemplateTag,
  isUpdateTarget,
  objectPatternPropNeedsReceiverRewrite,
  kebabToCamel,
  kebabToPascal,
  mayHaveSideEffects,
  peelFallbackReceiver,
  peelFallbackWrappers,
  peelNestedSequenceExpressions,
  propBindingIdentifier,
  resolveCallArgument,
  singleQuasiString,
  unwrapExportedDeclaration,
  unwrapInitValue,
  unwrapParens,
  unwrapRuntimeExpr,
  walkPatternIdentifiers,
} from './helpers/ast-patterns.js';
export {
  findUniqueName,
  isEntryPattern,
  isModulePattern,
  patternToRegExp,
  safeStringify,
  toStatelessRegExp,
  validatePatternList,
} from './helpers/pattern-matching.js';
export {
  POSSIBLE_GLOBAL_OBJECTS,
  buildSuperStaticMeta,
  createClassHelpers,
  globalProxyMemberName,
  resolveSuperImportName,
  symbolKeyToEntry,
} from './helpers/class-walk.js';
export {
  isCoreJSFile,
  lookupEntryModules,
  resolveImportPath,
  stripQueryHash,
} from './helpers/path-normalize.js';
export {
  buildOffsetToLine,
  mergeVisitors,
  parseDisableDirectives,
} from './helpers/source-scan.js';
