'use strict';
require('../modules/es.object.to-string');
require('../modules/es.array.iterator');
require('../modules/es.map.constructor');
require('../modules/es.string.iterator');
require('../modules/es.weak-map.constructor');
require('../modules/esnext.map.get-or-insert');
require('../modules/esnext.map.get-or-insert-computed');
require('../modules/esnext.weak-map.get-or-insert');
require('../modules/esnext.weak-map.get-or-insert-computed');
require('../modules/web.dom-collections.iterator');
