require('../src/es6.symbol');
require('../src/es6.object.statics');
require('../src/es6.object.prototype');
require('../src/es6.object.statics-accept-primitives');
require('../src/es6.function');
require('../src/es6.number.constructor');
require('../src/es6.number.statics');
require('../src/es6.math');
require('../src/es6.string');
require('../src/es6.array.statics');
require('../src/es6.array.prototype');
require('../src/es6.iterators');
require('../src/es6.regexp');
require('../src/es6.promise');
require('../src/es6.collections');
require('../src/es6.reflect');
module.exports = require('../src/$').core;