import "core-js/modules/es.symbol.iterator";
import "core-js/modules/es.object.to-string";
import "core-js/modules/es.array.iterator";
import "core-js/modules/es.string.iterator";
import "core-js/modules/es.string.bold";
import "core-js/modules/es.string.strike";
import "core-js/modules/web.dom-collections.iterator";
declare const tuple: [string, ...string[]];
const [first, second] = tuple;
first.bold();
second.strike();