import "core-js/modules/es.object.to-string";
import "core-js/modules/es.error.cause";
import "core-js/modules/es.error.is-error";
import "core-js/modules/es.array.iterator";
import "core-js/modules/es.string.repeat";
import "core-js/modules/es.string.pad-start";
import "core-js/modules/es.array.entries";
import "core-js/modules/es.array.keys";
import "core-js/modules/es.array-buffer.constructor";
import "core-js/modules/es.array-buffer.detached";
import "core-js/modules/es.array-buffer.transfer";
import "core-js/modules/es.array-buffer.transfer-to-fixed-length";
import "core-js/modules/es.array-buffer.species";
import "core-js/modules/es.array-buffer.to-string-tag";
import "core-js/modules/es.global-this";
import "core-js/modules/es.number.constructor";
import "core-js/modules/es.number.is-integer";
import "core-js/modules/es.regexp.constructor";
import "core-js/modules/es.regexp.escape";
import "core-js/modules/es.regexp.dot-all";
import "core-js/modules/es.regexp.exec";
import "core-js/modules/es.regexp.sticky";
import "core-js/modules/es.typed-array.uint8-array";
import "core-js/modules/es.typed-array.iterator";
import "core-js/modules/es.typed-array.at";
import "core-js/modules/es.typed-array.copy-within";
import "core-js/modules/es.typed-array.entries";
import "core-js/modules/es.typed-array.every";
import "core-js/modules/es.typed-array.fill";
import "core-js/modules/es.typed-array.filter";
import "core-js/modules/es.typed-array.find";
import "core-js/modules/es.typed-array.find-index";
import "core-js/modules/es.typed-array.find-last";
import "core-js/modules/es.typed-array.find-last-index";
import "core-js/modules/es.typed-array.for-each";
import "core-js/modules/es.typed-array.includes";
import "core-js/modules/es.typed-array.index-of";
import "core-js/modules/es.typed-array.join";
import "core-js/modules/es.typed-array.keys";
import "core-js/modules/es.typed-array.last-index-of";
import "core-js/modules/es.typed-array.map";
import "core-js/modules/es.typed-array.reduce";
import "core-js/modules/es.typed-array.reduce-right";
import "core-js/modules/es.typed-array.reverse";
import "core-js/modules/es.typed-array.set";
import "core-js/modules/es.typed-array.slice";
import "core-js/modules/es.typed-array.some";
import "core-js/modules/es.typed-array.sort";
import "core-js/modules/es.typed-array.species";
import "core-js/modules/es.typed-array.subarray";
import "core-js/modules/es.typed-array.to-locale-string";
import "core-js/modules/es.typed-array.to-reversed";
import "core-js/modules/es.typed-array.to-sorted";
import "core-js/modules/es.typed-array.to-string";
import "core-js/modules/es.typed-array.to-string-tag";
import "core-js/modules/es.typed-array.values";
import "core-js/modules/es.typed-array.with";
import "core-js/modules/es.uint8-array.from-hex";
import "core-js/modules/es.uint8-array.set-from-base64";
import "core-js/modules/es.uint8-array.set-from-hex";
import "core-js/modules/es.uint8-array.to-base64";
import "core-js/modules/es.uint8-array.to-hex";
import "core-js/modules/web.self";
// A `||` / `??` left read off the realm of a global core-js patches in place and ships no pure replacement of
// (`Number`, `RegExp`, the `Error` constructors, `ArrayBuffer`, `Uint8Array`) decides the selection as `Array`
// does: every engine carries it, so the right is dead - its constructor's modules stay out (`WeakSet`, `WeakMap`,
// `Iterator`, `DisposableStack`, `AsyncDisposableStack`) while the left's statics keep theirs; a disabled
// line injects nothing.
export const integer = (globalThis.Number || WeakSet).isInteger(1);
export const escaped = (globalThis.RegExp ?? WeakMap).escape('a.b');
export const errorCheck = (globalThis.TypeError || Iterator).isError(value);
export const view = 'isView' in (self.ArrayBuffer ?? DisposableStack);
export const fromHex = (globalThis.Uint8Array || AsyncDisposableStack).fromHex('ff');
// core-js-disable-next-line
export const kept = (globalThis.Number || Set).isNaN(value);