import _Array$from from "@core-js/pure/actual/array/from";
import _Object$assign from "@core-js/pure/actual/object/assign";
import _Promise$all from "@core-js/pure/actual/promise/all";
import _Promise$any from "@core-js/pure/actual/promise/any";
import _Promise$reject from "@core-js/pure/actual/promise/reject";
import _Promise$resolve from "@core-js/pure/actual/promise/resolve";
_Array$from(iter);
_Object$assign({}, a);
_Promise$resolve(1);
_Promise$reject(err);
_Promise$any([p1, p2]);
_Promise$all([1]);
_Promise$resolve(2);